### ISSUE TITLE
Credentials error

### ISSUE THREAD

**Issue by FrankFromGermany** [migueesc123/MeetupConnector#1]
Just tried it and after entering the key I'll get a message like "Failed to update data source credentials: 0 arguments were given to a function, however 1 was expected." Even if I change the language to English the error message is in German.

Offline, with Power BI Desktop no problems at all.

I bet you tested it yourself. I'm using the May 2018 personal gateway, which correctly shows the connector.
Any ideas?

**Comment by migueesc123** [comment]
Since the refresh-ability of Custom Connectors are still in preview, there are a couple of things that the Power BI Team are still ironing out. From the Custom Connector end, everything is set up correctly so it refreshes on the service.
I'd recommend that you [provide feedback](https://github.com/migueesc123/WooCommerceConnector) to the Power BI Custom Connectors team on their repo so they can fix any bugs that they have in their implementation asap. (I believe you already did this)
